// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mylibrary.repository;

import com.mylibrary.repository.BookRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BookRepository_Roo_Jpa_Repository {
    
    declare @type: BookRepository: @Transactional(readOnly = true);
    
}
